//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int СurriculumId { get; set; }
        public int EducationalProgram { get; set; }
        public int HourInYear { get; set; }
        public int HoursInWeek { get; set; }
        public System.DateTime StartDate { get; set; }
        public int MinScore { get; set; }
    
        public virtual EducationalProgram EducationalProgram1 { get; set; }
    }
}
