//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EducationalProgram()
        {
            this.Curriculum = new HashSet<Curriculum>();
        }
    
        public int EducationalProgramId { get; set; }
        public int StudyFiled { get; set; }
        public int Qualification { get; set; }
        public string ProgramName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Author { get; set; }
    
        public virtual Authors Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curriculum> Curriculum { get; set; }
        public virtual Qualification Qualification1 { get; set; }
        public virtual StudyField StudyField { get; set; }
    }
}
