//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyField()
        {
            this.EducationalProgram = new HashSet<EducationalProgram>();
        }
    
        public int StudyFieldId { get; set; }
        public string StudyFieldName { get; set; }
        public int Department { get; set; }
    
        public virtual Department Department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalProgram> EducationalProgram { get; set; }
    }
}
